export type FilterCategory = {
  label: string;
  options: string[];
};

export const FILTER_CATEGORIES: FilterCategory[] = [
  {
    label: "Work Modality",
    options: ["Fully Remote (global)", "Fully Remote (local)", "Hybrid", "On-site"],
  },
  {
    label: "Type of Contract",
    options: [
      "Permanent FT",
      "Permanent PT",
      "Fixed term contract",
      "Temporary/Short-term",
      "Freelance/Consultancy",
      "Internship (paid only)",
      "Volunteering",
      "Fellowship/Traineeship",
      "International Volunteering (UNV, etc)",
      "Civic Service",
    ],
  },
  {
    label: "Thematic Area",
    options: [
      "Human Rights & Governance",
      "Environment & Climate",
      "Gender Equality & Social Inclusion (GESI)",
      "Humanitarian Action",
      "Peacebuilding/Conflict Resolution",
      "Development Cooperation",
      "Public Health",
      "Migration & Displacement",
      "Education",
      "International Law",
      "Water, Sanitation & Hygiene (WASH)",
      "Tech/Digital for Development",
      "Social Economy",
      "Indigenous Rights",
      "Youth",
      "Community Development",
      "Government",
      "LGBTQI+ Rights",
      "Economic Development & Trade",
      "Arts, Culture & Media",
      "Other",
    ],
  },
  {
    label: "Job Function",
    options: [
      "Communications",
      "Digital Communications",
      "Media & PR",
      "Advocacy & Campaigns",
      "Content & Editorial",
      "Design & Creative",
      "Admin & Office Support",
      "Finance & Accounting",
      "Human Resources",
      "Procurement & Logistics",
      "Operations",
      "Legal & Compliance",
      "IT & Digital Systems",
      "Programme Management",
      "Project Support",
      "Monitoring, Evaluation & Learning",
      "Training & Capacity Building",
      "Community Engagement & Volunteer Management",
      "Policy",
      "Strategy & Organisational Development",
      "Data & Research",
      "Grants & Partnerships",
      "Fundraising & Resource Mobilisation",
      "Business Development & Proposal Writing",
      "Executive Leadership & Management",
    ],
  },
  {
    label: "Location",
    options: [
      "🇨🇳 China",
      "🇯🇵 Japan",
      "🇰🇷 South Korea",
      "🇰🇵 North Korea (DPRK)",
      "🇲🇳 Mongolia",
      "🇹🇼 Taiwan",
      "🇭🇰 Hong Kong SAR",
      "🇲🇴 Macao SAR",
      "🇧🇳 Brunei Darussalam",
      "🇰🇭 Cambodia",
      "🇮🇩 Indonesia",
      "🇱🇦 Laos",
      "🇲🇾 Malaysia",
      "🇲🇲 Myanmar",
      "🇵🇭 Philippines",
      "🇸🇬 Singapore",
      "🇹🇭 Thailand",
      "🇹🇱 Timor-Leste",
      "🇻🇳 Vietnam",
      "🇦🇫 Afghanistan",
      "🇧🇩 Bangladesh",
      "🇧🇹 Bhutan",
      "🇮🇳 India",
      "🇲🇻 Maldives",
      "🇳🇵 Nepal",
      "🇵🇰 Pakistan",
      "🇱🇰 Sri Lanka",
      "🇰🇿 Kazakhstan",
      "🇰🇬 Kyrgyzstan",
      "🇹🇯 Tajikistan",
      "🇹🇲 Turkmenistan",
      "🇺🇿 Uzbekistan",
      "🇫🇲 Micronesia (Federated States of)",
      "🇫🇯 Fiji",
      "🇨🇰 Cook Islands",
      "🇰🇮 Kiribati",
      "🇲🇭 Marshall Islands",
      "🇳🇷 Nauru",
      "🇳🇿 New Zealand",
      "🇳🇺 Niue",
      "🇵🇼 Palau",
      "🇵🇬 Papua New Guinea",
      "🇼🇸 Samoa",
      "🇸🇧 Solomon Islands",
      "🇹🇴 Tonga",
      "🇹🇻 Tuvalu",
      "🇻🇺 Vanuatu",
      "🇦🇺 Australia",
      "🇳🇨 New Caledonia (France)",
      "🇵🇫 French Polynesia (France)",
      "+ Africa",
      "+ Europe",
      "+ Middle East",
      "+ North America",
      "+ South America",
    ],
  },
];
